//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1WCFClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Контракт генерации сообщений с именем HelloWorldResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WpfApp1WCFClient.ServiceReference1.HelloWorldResponse HelloWorld(WpfApp1WCFClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApp1WCFClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WpfApp1WCFClient.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем number1 из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Summ", ReplyAction="*")]
        WpfApp1WCFClient.ServiceReference1.SummResponse Summ(WpfApp1WCFClient.ServiceReference1.SummRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Summ", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApp1WCFClient.ServiceReference1.SummResponse> SummAsync(WpfApp1WCFClient.ServiceReference1.SummRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1WCFClient.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WpfApp1WCFClient.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1WCFClient.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WpfApp1WCFClient.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SummRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Summ", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1WCFClient.ServiceReference1.SummRequestBody Body;
        
        public SummRequest() {
        }
        
        public SummRequest(WpfApp1WCFClient.ServiceReference1.SummRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SummRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string number1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string number2;
        
        public SummRequestBody() {
        }
        
        public SummRequestBody(string number1, string number2) {
            this.number1 = number1;
            this.number2 = number2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SummResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SummResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1WCFClient.ServiceReference1.SummResponseBody Body;
        
        public SummResponse() {
        }
        
        public SummResponse(WpfApp1WCFClient.ServiceReference1.SummResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SummResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SummResult;
        
        public SummResponseBody() {
        }
        
        public SummResponseBody(string SummResult) {
            this.SummResult = SummResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WpfApp1WCFClient.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WpfApp1WCFClient.ServiceReference1.WebService1Soap>, WpfApp1WCFClient.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1WCFClient.ServiceReference1.HelloWorldResponse WpfApp1WCFClient.ServiceReference1.WebService1Soap.HelloWorld(WpfApp1WCFClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WpfApp1WCFClient.ServiceReference1.HelloWorldRequest inValue = new WpfApp1WCFClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WpfApp1WCFClient.ServiceReference1.HelloWorldRequestBody();
            WpfApp1WCFClient.ServiceReference1.HelloWorldResponse retVal = ((WpfApp1WCFClient.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1WCFClient.ServiceReference1.HelloWorldResponse> WpfApp1WCFClient.ServiceReference1.WebService1Soap.HelloWorldAsync(WpfApp1WCFClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1WCFClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WpfApp1WCFClient.ServiceReference1.HelloWorldRequest inValue = new WpfApp1WCFClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WpfApp1WCFClient.ServiceReference1.HelloWorldRequestBody();
            return ((WpfApp1WCFClient.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1WCFClient.ServiceReference1.SummResponse WpfApp1WCFClient.ServiceReference1.WebService1Soap.Summ(WpfApp1WCFClient.ServiceReference1.SummRequest request) {
            return base.Channel.Summ(request);
        }
        
        public string Summ(string number1, string number2) {
            WpfApp1WCFClient.ServiceReference1.SummRequest inValue = new WpfApp1WCFClient.ServiceReference1.SummRequest();
            inValue.Body = new WpfApp1WCFClient.ServiceReference1.SummRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            WpfApp1WCFClient.ServiceReference1.SummResponse retVal = ((WpfApp1WCFClient.ServiceReference1.WebService1Soap)(this)).Summ(inValue);
            return retVal.Body.SummResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1WCFClient.ServiceReference1.SummResponse> WpfApp1WCFClient.ServiceReference1.WebService1Soap.SummAsync(WpfApp1WCFClient.ServiceReference1.SummRequest request) {
            return base.Channel.SummAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1WCFClient.ServiceReference1.SummResponse> SummAsync(string number1, string number2) {
            WpfApp1WCFClient.ServiceReference1.SummRequest inValue = new WpfApp1WCFClient.ServiceReference1.SummRequest();
            inValue.Body = new WpfApp1WCFClient.ServiceReference1.SummRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            return ((WpfApp1WCFClient.ServiceReference1.WebService1Soap)(this)).SummAsync(inValue);
        }
    }
}
